name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Barani CI/CD
        run:
             echo "We are Learning About Devop's Today"
      - name: Step 1
             echo "We are Learning About Devop's Today"
      - name: Step 2
             echo "We are Learning About Devop's Today"
      - name: Step 3
             echo "We are Learning About Devop's Today"
      - name: Step 4
             echo "We are Learning About Devop's Today"
      - name: Step 5
             echo "We are Learning About Devop's Today"
             
        
            
